name:                merckinator-website
version:             0.1.0.0
github:              "githubuser/merckinator-website"
license:             BSD3
author:              "Jeff Merckens"
maintainer:          "jeff.merckens@gmail.com"
copyright:           "2020 Jeff Merckens"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A personal website trying out different tech
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/merckinator-website#readme>

dependencies:
- base >= 4.7 && < 5
- blaze-html
- scotty

library:
  source-dirs: src

executables:
  merckinator-website-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - merckinator-website

tests:
  merckinator-website-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - merckinator-website
